apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: external-secrets
type: Opaque
data:
  access-key: QUtJQVlSSDVNWDVQQ0JQWFMzVjQ=
  secret-access-key: VEc3YytCcUZtVUEyd1lIWkwxaFM5VS93Z2c0TmxNTHFBT09yNTVxaw==
