apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-my-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/Joy-it-code/gitops-project-1.git
    targetRevision: main
    path: helm-app/my-app
    plugin:
      name: avp-plugin  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
