apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-my-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Joy-it-code/gitops-project-1.git
    targetRevision: main
    path: kustomize-app/my-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
