apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myapp-password
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: myapp-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: myapp/password
