apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: default
spec:
  containers:
  - name: myapp
    image: nginx:latest
    env:
    - name: APP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-secret
          key: password