apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
data:
  resource.customizations: |
    external-secrets.io/ExternalSecret:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "Ready" and condition.status == "True" then
              hs.status = "Healthy"
              hs.message = condition.message or "ExternalSecret is ready"
              return hs
            end
          end
          hs.status = "Degraded"
          hs.message = "ExternalSecret is not ready"
        else
          hs.status = "Degraded"
          hs.message = "Status not found"
        end
        return hs
  resource.ignoreDifferences: |
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /metadata/annotations
        